version: "1.2"



services:
  emongo:
    image: mongo:4
    container_name: emondb
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - "8081:8081"
  
  przemdb:
    image: mysql:8.0.33
    container_name: przemdb
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret
      - MYSQL_DATABASE=books

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"